name: Custom Docker Image Auto Release

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The branch to build
        default: main

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          images: |
            name=ghcr.io/${{ github.repository_owner }}/chatwoot
          tags: |
            type=raw,value=${{ github.event.inputs.branch }},enable=true

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          platforms: linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}